version: "3.8"

services:
  # Fluent Bit for log collection (future integration)
  fluent-bit:
    image: fluent/fluent-bit:2.2
    container_name: ecommerce-fluent-bit
    volumes:
      - ./monitoring/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./monitoring/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    ports:
      - "24224:24224"
    networks:
      - ecommerce-network
    profiles: ["logging"]

  # Grafana Loki for log aggregation (future integration)
  loki:
    image: grafana/loki:2.9.0
    container_name: ecommerce-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - ecommerce-network
    profiles: ["logging"]

volumes:
  loki_data:

networks:
  ecommerce-network:
    external: true
